server:
  port: 8082
  servlet:
    context-path: /message
spring:
  application:
    name: zmlm-message
  data:
    mongodb:
      host: localhost   #同127.0.0.1
      port: 27017
      database: zmlm-message    #指定操作的数据库