server:
  port: 8081
  servlet:
    context-path: /core
spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3307/zmlm?characterEncoding=utf-8&serverTimezone=UTC
      username: root
      password: root
  redis:
    port: 6379
    host: localhost
    database: 1
#  elasticsearch:
#    rest:
#      uris: http://localhost:9200
mybatis-plus:
  mapper-locations: classpath:dao/*.xml
  global-config:
    db-config:
      id-type: assign_uuid
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
